### PR TITLE
Add Support for More Launchers (HiOS, ColorOS, OxygenOS, Before, Nothing)

### PR DESCRIPTION
**Pull request by moertel**
This PR adds a fleet of new launchers for devices like OnePlus, OPPO, Realme and TECNO.

### ColorOS / OxygenOS

These initially existed as ColorOS for Realme and OPPO, and OxygenOS for OnePlus. Starting with Android 12, they've begun merging both launchers which leads to a matrix of available combinations. Luckily, the instructions are consistent when triggered via homescreen (as opposed to their vastly differing wording in the "Settings" area).

A visible side-effect is that they no longer report as `com.oppo.launcher` and `net.oneplus.launcher` but instead only as `com.android.launcher`. As this is not unique, at all, it leads to a rather complicated detection mechanism.

I decided to detect `com.android.launcher` as a "Stock Launcher" (with a green Android icon) but swap these out for ColorOS and OxygenOS when I spot them (based on the device manufacturer). To make sure we don't display unexpected stuff, `com.android.launcher` will not be listed for any other devices.

The below devices are "Overseas" devices, so I can't speak to what happens with Chinese ROMs (which are said to report another launcher variant `HydrogenOS` (or `H2OS`). I don't have access to such devices, so cannot experiment.

<details><summary><b>📱 OnePlus</b> device test list (click to expand)</summary>

| Device | Android | Launcher | Detected | Correct? | 🎬 | Supported |
| ------- | ------- | ---------- | --------- | --------- | -- | ---------- |
| OnePlus 11 | 14 (Beta) | `com.android.launcher` | ColorOS | ✅ | | yes |
| OnePlus Nord 2 | 12 | `com.android.launcher` | ColorOS | ✅ | | yes |
| OnePlus Nord CE | 11 | `net.oneplus.launcher` | OxygenOS | ✅ | | yes |
| OnePlus Nord 2 | 11 | `net.oneplus.launcher` | OxygenOS | ✅ | | yes |
| OnePlus 9 | 11 | `net.oneplus.launcher` | OxygenOS | ✅ | | yes |
| OnePlus 7T | 11 | `net.oneplus.launcher` | OxygenOS | ✅ | ✅ | yes |
| OnePlus 7T | 10 | `net.oneplus.launcher` | OxygenOS | ✅ | | yes |
| OnePlus 7 | 9 | `net.oneplus.launcher` | OxygenOS | ✅ | | yes |
| OnePlus 6T | 9 | `net.oneplus.launcher` | OxygenOS | ✅ | | yes |

</details>
<details><summary><b>📱 OPPO</b> device test list (click to expand)</summary>

| Device | Android | Launcher | Detected | Correct? | 🎬 | Supported |
| ------- | -------- | --------- | --------- | --------- | -- | ---------- |
| OPPO Reno8 | 12 | `com.android.launcher` | ColorOS | ✅ | | yes |
| OPPO K10 | 11 | `com.oppo.launcher` | ColorOS | ✅ | ✅ | yes |
| OPPO A54 | 11 | `com.oppo.launcher` | ColorOS | ✅ | | yes |
| OPPO F17 | 11 | `com.oppo.launcher` | ColorOS | ✅ | | yes |
| OPPO F17 | 10 | `com.oppo.launcher` | ColorOS | ✅ | | no |
| OPPO A15 | 10 | `com.oppo.launcher` | ColorOS | ✅ | | no |
| OPPO A12 | 9 | `com.oppo.launcher` | ColorOS | ✅ | | no |

</details>
<details><summary><b>📱 realme</b> device test list (click to expand)</summary>

| Device | Android | Launcher | Detected | Correct? | 🎬 | Supported |
| ------- | -------- | --------- | --------- | --------- | -- | ---------- |
| realme GT2 Pro | 12 | `com.android.launcher` | ColorOS | ✅ | | yes |
| realme C21 Y | 11 | `com.android.launcher3` | ⚠️ | ⚠️ | | no |
| realme 8i | 11 | `com.android.launcher` | Realme UI | ✅ | | yes |
| realme 7i | 10 | `com.oppo.launcher` | ColorOS | ✅ | | no |
| realme 5i | 10 | `com.oppo.launcher` | ColorOS | ✅ | | no |

Something about `realme C21 Y` is odd but as the `launcher3` doesn't support icon packs anyway, I'm ok with it not detecting anything here.
</details>

----

### HiOS

Stock on TECNO devices, but can be installed to other devices from PlayStore.
<details><summary>📱 Device test list (click to expand)</summary>

| Launcher | Device | Android Version | Works | Comment |
| --------- | ------- | ---------------- | ------ | ---------- |
| HiOS | TECNO SPARK 7 | 11 | ✅ | |

</details>

----

### Before Launcher
 * I chatted with their devs and kindly enough they implemented a "direct apply" option to be released with their next update. That's why currently the manual instructions are provided as a fallback. Update: This is now live with Before Launcher version 6.1.1.
  * It doesn't support adaptive icons just yet (and according to the devs won't for quite a while), so icon pack devs will need to decide whether or not to include it. I added this as a comment for now.

### CODE REVIEW

**Comment by moertel** [comment]
HiOS demo. Watch the "Chrome" icon on the home screen change. :)

https://github.com/zixpo/candybar/assets/1823966/c5a3faa0-8796-4dc3-8cbb-6cca7d90a4eb

**Comment by moertel** [comment]
@sarsamurmu after testing thoroughly with all those devices listed above, I'm reasonably sure I've captured all "overseas-market" OnePlus, OPPO and realme devices. One can never be 100% sure, I guess, but I'm happy to revisit it in case I get feedback from users (or other icon devs). This is now ready for review!

**Comment by sarsamurmu** [comment]
Thanks for your hard work. By the way, where did you get all these devices for testing? Did you use an online service? 🤔

**Comment by moertel** [comment]
Yep, an online service. I subscribed to `lambdatest.com` as they offer real devices (not just emulators) and are somewhat affordable. I figured it was worth it to see the different launchers through our users' eyes and it even allows to record screencapture videos, so I can use it for tutorials.

**Comment by moertel** [comment]
FYI, this change has been live for ~1000 users in my icon packs' beta versions. No errors so far. I'm releasing it to the wild in about 2 days, so I can let you know if anything looks odd or needs improvement.

The devs from Before Launcher just let me know that version 6.1.1 went live, including the Intent needed for [de3721e](https://github.com/zixpo/candybar/pull/152/commits/de3721eebf46a8fb409ea41f13d653f271605b41). We tested it and it works.

**Comment by Donnnno** [comment]
wowww, you're doing so much great work lately for the dashboard. Thanks a lot for that <3

**Comment by moertel** [comment]
No exceptions, no issues. 🚀 All good from my side and good to merge, @sarsamurmu! I see especially `Nothing Launcher` and `OxygenOS` rushing into the top 10 launchers for my user base, so if that's representative it will be a huge win for many icon pack devs.

I really appreciate the kind words from you all! 🥹

**Pull request merged**
