### PR TITLE
Control icon reshaping in Nova launcher

### PR DESCRIPTION
**Pull request by moertel**
This commit adds a new configuration option for using "direct apply" in Nova launcher. For icon packs with intentionally transparent backgrounds, Nova unfortunately defaults to its "Reshape legacy icons" setting being "ON" and adding backgrounds. For monochrome packs, it works ok even if unexpected for users. For colourful packs, the setting often guesses the background colours very wrong leading to ugly and illegible results.

The Nova team agreed on exposing this feature to devs via an Intent Extra. The default behaviour "ON" is kept but can be overridden by the icon pack to "OFF" (disabling it for all icons) or "AUTO" (disabling it for unthemed icons only).

Visual example of the setting being "OFF" (left side) vs. "ON" (right side; Nova's default):

Refs https://discord.com/channels/466300922767736844/1098328998532096142/1109611038401368084

### CODE REVIEW

**Comment by moertel** [comment]
This feature is not released by Nova yet. I'll update this PR when it's become available.

**Comment by Donnnno** [comment]
This is just great, you're on fire! 🔥

**Comment by sarsamurmu** [comment]
Awesome!

**Comment by apex2504** [comment]
This is now supported in Nova Launcher as of yesterday's 8.0.6 beta.

**Comment by moertel** [comment]
I can confirm it works like a charm! :) Thanks again for bringing this to Nova, @apex2504, much appreciated!

@sarsamurmu this is ready to merge

**Comment by sarsamurmu** [comment]
Cool! Let's get it merged.

**Pull request merged**
