### PR TITLE
Fix: No field mMaxHeight in class Landroid/widget/ImageView (Android Q)

### PR DESCRIPTION
**Pull request by michelelacorte**

### CODE REVIEW

**Comment by michelelacorte** [comment]
Hi @sarsamurmu why this is closed and not merged?

**Comment by sarsamurmu** [comment]
That was a mistake.

**Comment by michelelacorte** [comment]
When this commit will be available ?

**Comment by sarsamurmu** [comment]
On next update. But if you want to use it now then use `8a87b79e7d` as CandyBar version.

**Pull request merged**
