### PR TITLE
Add BlackBerry Launcher

### PR DESCRIPTION
**Pull request by dalight13**
Let me know if something is missing

Thanks

### CODE REVIEW

**Comment by dalight13** [comment]
I tested it by including the branch in my project, the BlackBerry Launcher is showing up in the installed launchers section but when I select it, it tells my it's not installed.

Not sure if I missed something or it's just not compatible.

Thanks again!

**Comment by sarsamurmu** [comment]
That's great. Can you make the icon square and full with no padding? Like this - https://github.com/zixpo/candybar/blob/master/library/src/main/res/drawable-xxxhdpi/ic_launcher_lawnchair.png

**Comment by dalight13** [comment]
Done my friend.

Thanks

**Comment by sarsamurmu** [comment]
Thanks for your contribution.

**Comment by dalight13** [comment]
How do I use it? Do I have to wait for beta.6.7?

Maybe it's just not downloading the new version in my project and that's why the changes are not showing up..

Thanks again!

**Comment by sarsamurmu** [comment]
Go to `res/values/launchers.xml` and add `blackberry`. Use `1d863bef1a` as version number. Like `implementation 'com.github.zixpo:candybar:1d863bef1a'`.

**Comment by dalight13** [comment]
Thanks the new version number works.

There's an issue though, I downloaded the Microsoft Launcher to compare as they both don't support direct install and I get the following results.

They both show up on top as Installed Launcher.

When I tap the Microsoft Launcher, it tells me it doesn't support direct apply. If I tap CANCEL, it stays inside the icon pack and if I tap OK it sends me to the Microsoft Launcher Homescreen which is good.

When I tap the BlackBerry Launcher, it tells me it doesn't support direct apply. If I tap CANCEL, it stays inside the icon pack but if I tap OK it tells me the BlackBerry Launcher is not installed.

Thanks again!

**Comment by sarsamurmu** [comment]
No worries, I fixed that. You can use it on v3.5.0-beta.6.7 which is not yet released.

**Comment by dalight13** [comment]
Great thank you very much!!

**Pull request merged**
