### PR TITLE
Add Samsung OneUI

### PR DESCRIPTION
**Pull request by moertel**
This PR adds functionality to detect Samsung OneUI launcher and gives instructions
to apply third-party icon packs.

Samsung's OneUI launcher version is tightly coupled to the Android OS version.
Starting OneUI 3.1.1, icon theming is supported on Android 11, foldable devices only[1]
Starting OneUI 4.0, icon theming is supported on all Android 12 devices[2]

Sadly it's impossible to detect the OneUI version programmatically[3].

Technically it's incorrect to report all Android 11 devices as incompatible but the
only other option is to try and list out all device models individually. This commit
adds the display of a "please update to Android 12" message to anyone running Android
11 or lower, and displays step-by-step theming instructions to everyone else.

[1] https://www.androidpolice.com/how-to-use-custom-icon-packs-on-samsung-one-ui-4/
[2] https://en.wikipedia.org/wiki/One_UI#One_UI_4_2
[3] https://github.com/zixpo/candybar/pull/122#issuecomment-1510379686

## Behaviour & UI

| Displayed on Android 11 or lower | Displayed on Android 12 and up |
|---------------------------------|---------------------------------|
| "OK" opens software update      | "OK" opens "Theme Park" in Galaxy Store |
|  |  |

## Verified

The behaviour described above has been tested on the devices and Android versions below:

| | Device | Model | Android | One UI | Behaviour |
|-|--------|-------|---------|--------|-----------|
| ✅ | S10 Duos | SM-G973F | 9 | 1.1 | Launcher detected, sees ⚠️ "please update" dialog |
| ✅ | S10 Duos | SM-G973F | 10 | 2.5 | Launcher detected, sees ⚠️ "please update" dialog |
| ✅ | S10 Duos | SM-G973F | 11 | 3.1 | Launcher detected, sees ⚠️ "please update" dialog |
| ✅ | S10 Duos | SM-G973F | 12 | 4.0 | Launcher detected, sees 📗 step-by-step instructions |
| ✅ | S23 Ultra | SM-S918B | 13 | 5.1 | Launcher detected, sees 📗 step-by-step instructions |

### CODE REVIEW

**Comment by Donnnno** [comment]
Wow! This is huge!!! Thank you for this :))

**Comment by moertel** [comment]
Demo video:

https://user-images.githubusercontent.com/1823966/232307563-ad589980-90ce-4803-a2b6-fb2ab2913b88.mp4

**Comment by moertel** [comment]
@Donnnno honestly, one more bad review on GooglePlay because of this and I would have gone seriously mad. 😅 Luckily I have a few Samsung devices with various versions of Android and OneUI that I can test with, but I'll also publish this as Beta to my own icon packs next week and collect feedback/bugs.

It's always tricky to give folks more complex instructions than just "click here and be done", so I'm contemplating showing a tutorial right when they open the app - giving instructions specific to their current launcher. (Let me know if you're interested in brainstorming this.)

**Comment by moertel** [comment]
https://www.androidpolice.com/how-to-use-custom-icon-packs-on-samsung-one-ui-4/
> How to apply custom icon packs. Before we begin, we should clarify that while we refer to this as a One UI 4 feature, it was **introduced in One UI 3.1.1**. That version was exclusive to foldable phones, though, so icon packs have only really made it to the majority of Samsung phones with One UI 4.

Looks like some One UI version detection is necessary. I'll gradually update my old Samsung through One UI 1, 2, 3, 4 and 5 and see where the "Icon" option starts appearing in Theme Park, just to cross-check what that article says.

**Comment by moertel** [comment]
@sarsamurmu this is now ready for review. I falsely tell users of foldable Samsung devices on Android 11 that their OneUI version is incompatible but as there is no way to detect the OneUI version programmatically, and as non-foldable devices on Android 11 are definitely not compatible, this was the best I could do.

Screenshots and demo video included in the comments. I'm releasing this to my own users this week and will report back if I spot issues.

**Comment by moertel** [comment]
FYI, I wanted to report back that this has now been published in my own icon packs for little over a week and it's working great. No complaints, and quite a few comments from happy Samsung users.

**Pull request merged**
